networks:
  homelab:
    external: true

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    env_file: .env
    volumes:
      - ./conf:/config
      - ${MEDIA_PATH}:/media
    restart: unless-stopped
    ports:
      - "32400:32400"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/web"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - homelab
