networks:
  homelab:
    external: true

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run homelab
    volumes:
      - ./conf:/etc/cloudflared:ro
    networks:
      - homelab
