networks:
  homelab:
    name: homelab
    external: true

services:
  cloudflared:
    extends:
      file: core/cloudflared/docker-compose.yml
      service: cloudflared

  wireguard:
    extends:
      file: core/wireguard/docker-compose.yml
      service: wireguard

  jellyfin:
    extends:
      file: apps/jellyfin/docker-compose.yml
      service: jellyfin

  sonarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: sonarr

  radarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: radarr

  prowlarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: prowlarr

  qbittorrent:
    extends:
      file: apps/qbittorrent/docker-compose.yml
      service: qbittorrent

  plex:
    extends:
      file: apps/plex/docker-compose.yml
      service: plex
