networks:
  homelab:
    name: homelab
    external: true

services:
  cloudflared:
    extends:
      file: core/cloudflared/docker-compose.yml
      service: cloudflared

  jellyfin:
    extends:
      file: apps/jellyfin/docker-compose.yml
      service: jellyfin
