networks:
  homelab:
    name: homelab
    external: true

services:
  cloudflared:
    extends:
      file: core/cloudflared/docker-compose.yml
      service: cloudflared

  heimdall:
    extends:
      file: core/heimdall/docker-compose.yml
      service: heimdall

  netdata:
    extends:
      file: core/netdata/docker-compose.yml
      service: netdata

  wireguard:
    extends:
      file: core/wireguard/docker-compose.yml
      service: wireguard

  jellyfin:
    extends:
      file: apps/jellyfin/docker-compose.yml
      service: jellyfin

  jellyseerr:
    extends:
      file: apps/jellyseerr/docker-compose.yml
      service: jellyseerr

  sonarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: sonarr

  radarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: radarr

  prowlarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: prowlarr

  bazarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: bazarr

  qbittorrent:
    extends:
      file: apps/qbittorrent/docker-compose.yml
      service: qbittorrent

  plex:
    extends:
      file: apps/plex/docker-compose.yml
      service: plex

  tautulli:
    extends:
      file: apps/tautulli/docker-compose.yml
      service: tautulli

  jackett:
    extends:
      file: apps/jackett/docker-compose.yml
      service: jackett
