networks:
  homelab:
    name: homelab
    external: true

services:
  cloudflared:
    extends:
      file: core/cloudflared/docker-compose.yml
      service: cloudflared

  dozzle:
    extends:
      file: core/dozzle/docker-compose.yml
      service: dozzle

  dozzle-agent:
    extends:
      file: core/dozzle/docker-compose.yml
      service: dozzle-agent

  fail2ban:
    extends:
      file: core/fail2ban/docker-compose.yml
      service: fail2ban

  heimdall:
    extends:
      file: core/heimdall/docker-compose.yml
      service: heimdall

  monit:
    extends:
      file: core/monit/docker-compose.yml
      service: monit

  netdata:
    extends:
      file: core/netdata/docker-compose.yml
      service: netdata

  organizr:
    extends:
      file: core/organizr/docker-compose.yml
      service: organizr

  wireguard:
    extends:
      file: core/wireguard/docker-compose.yml
      service: wireguard

  filebrowser:
    extends:
      file: apps/filebrowser/docker-compose.yml
      service: filebrowser

  jackett:
    extends:
      file: apps/jackett/docker-compose.yml
      service: jackett

  jellyfin:
    extends:
      file: apps/jellyfin/docker-compose.yml
      service: jellyfin

  jellyseerr:
    extends:
      file: apps/jellyseerr/docker-compose.yml
      service: jellyseerr

  pairdrop:
    extends:
      file: apps/pairdrop/docker-compose.yml
      service: pairdrop

  plex:
    extends:
      file: apps/plex/docker-compose.yml
      service: plex

  qbittorrent:
    extends:
      file: apps/qbittorrent/docker-compose.yml
      service: qbittorrent

  searxng:
    extends:
      file: apps/searxng/docker-compose.yml
      service: searxng

  redis:
    extends:
      file: apps/searxng/docker-compose.yml
      service: redis

  bazarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: bazarr

  prowlarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: prowlarr

  radarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: radarr

  sonarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: sonarr

  tautulli:
    extends:
      file: apps/tautulli/docker-compose.yml
      service: tautulli
