networks:
  homelab:
    name: homelab
    external: true

services:
  cloudflared:
    extends:
      file: core/cloudflared/docker-compose.yml
      service: cloudflared

  jellyfin:
    extends:
      file: apps/jellyfin/docker-compose.yml
      service: jellyfin

  sonarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: sonarr

  radarr:
    extends:
      file: apps/servarr/docker-compose.yml
      service: radarr
