networks:
  homelab:
    name: homelab
    external: true

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    env_file: .env
    ports:
      - "8989:8989"
    volumes:
      - ./sonarr/conf:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${MEDIA_PATH}/downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - homelab

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file: .env
    ports:
      - "7878:7878"
    volumes:
      - ./radarr/conf:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - homelab
