networks:
  homelab:
    external: true

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    env_file: .env
    volumes:
      - ./conf:/data
    ports:
      - 8085:8085
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - dozzle-agent
    networks:
      - homelab

  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    restart: unless-stopped
    networks:
      - homelab
