version: '2.4'

networks:
  homelab:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: .env
    volumes:
      - ./conf:/config
      - ${MEDIA_PATH}/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    mem_limit: 2g
    cpus: 1.0
    cpu_shares: 512
    pids_limit: 100
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - homelab
