networks:
  homelab:
    external: true

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    env_file: .env
    volumes:
      - ${MEDIA_PATH}:/srv
      - ./conf/database:/database
      - ./conf/log:/log
    ports:
      - "8084:8084"
    restart: unless-stopped
    networks:
      - homelab
