networks:
  homelab:
    name: homelab
    external: true

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file: .env
    ports:
      - "5055:5055"
    volumes:
      - ./conf:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - homelab
